spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:1313/postgres
    username: Vovan
    password: postgres
    driverClassName: org.postgresql.Driver